version: '3'

services: 
  postgis:
    image: postgis/postgis:12-3.0-alpine
    environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_USER: ${DB_USER}
    volumes:
      - postgis:/var/lib/postgresql/data
  redmine:
    build: .
    environment:
      DB_HOST: postgis
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RAILS_ENV: production
      RAILS_MEMORY_LIMIT: ${RAILS_MEMORY_LIMIT}
      PUMA_KILLER_LOG: ${PUMA_KILLER_LOG}
      RAILS_LOG_TO_STDOUT: ${RAILS_LOG_TO_STDOUT}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "3000:3000"
    depends_on:
      - postgis

volumes: 
  postgis:

